// Code Generated by Sidekick is for learning and experimentation purposes only.
import SwiftUI
import MapKit
import Combine
import UIKit
import CoreGraphics
import Foundation

// Define a new view for displaying pilot details
struct PilotDetailView: View {
    var pilotTrack: PilotTracks

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text("Pilot Name: \(pilotTrack.pilotName)")
            Text("Date and Time: \(pilotTrack.dateTime)")
            Text("Coordinates: \(pilotTrack.coordinates.latitude), \(pilotTrack.coordinates.longitude)")
            Text("Altitude: \(pilotTrack.altitude) meters")
            Text("Speed: \(pilotTrack.speed) km/h")
            Text("Heading: \(pilotTrack.heading)°")
            Text("Flight Start Time: \(pilotTrack.oldestDateTime)")
            Text("Flight Duration: \(pilotTrack.flightDuration) minutes")
            Text("In Emergency: \(pilotTrack.inEmergency ? "Yes" : "No")")
        }
        .padding()
    }
}
